# Generated by Django 5.1.6 on 2025-02-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecular_id', models.CharField(max_length=255, unique=True)),
                ('name', models.TextField()),
                ('smiles', models.TextField()),
                ('hb_donors', models.IntegerField()),
                ('hb_acceptors', models.IntegerField()),
                ('clogp', models.FloatField()),
                ('num_rot_bonds', models.IntegerField()),
                ('num_rings_alt', models.IntegerField()),
                ('tpsa', models.FloatField()),
                ('mol_weight', models.FloatField()),
                ('formula', models.TextField()),
                ('logD', models.FloatField()),
            ],
        ),
    ]
