# Generated by Django 5.1.6 on 2025-02-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='molecular_id',
            field=models.CharField(max_length=255),
        ),
    ]
